baseURL: https://luanletien.github.io
languageCode: vietnam
title: Le Tien Luan
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true

languages:
  vn:
    languageName: ":vietnam:"
    weight: 1
    taxonomies:
      category: Danh mục
      tag: tags
      series: Series
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: WiKi
          url: https://github.com/
        - name: Discord
          url: https://discord.gg/

  en:
    languageName: ":en:"
    languageAltTitle: English
    weight: 2
    title: PaperModL2
    taxonomies:
      category: categories
      tag: tags
      series: series
    profileMode:
      enabled: true
      title: PaperMod
      imageUrl: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f317.svg"
      imageTitle: ProfileMode image
      subtitle: "☄️ Fast | ☁️ Fluent | 🌙 Smooth | 📱 Responsive"
      buttons:
        - name: Blog
          url: posts
        - name: Profile Mode
          url: https://github.com/
    menu:
      main:
        - name: Archive
          url: archives/
          weight: 5
        - name: FRTags
          url: frtags
          weight: 10
        - name: FRCategories
          url: frcategories
          weight: 10
        - name: FRSeries
          url: frseries
          weight: 10
        - name: NullLink
          url: "#"

outputs:
  home:
    - HTML
    - RSS
    - JSON


