baseURL: https://luanletien.github.io
languageCode: vietnam
title: Le Tien Luan
theme: PaperMod

enableRobotsTXT: true
enableEmoji: true

buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true

permalinks: 
  post: "/:title/"

defaultContentLanguage: vn
defaultContentLanguageInSubdir: true
languages:
  vn:
    languageName: ":vietnam:"
    languageAltTitle: Việt Nam
    weight: 1
    title: Lê Tiến Luân
    subtitle: "Tôi là Luân! Rất vui được chia sẽ những hiểu biết của tôi về lĩnh vực Data Analyst với mọi người!"
    taxonomies:
      category: Danh mục
      tag: tags
      series: Series
    profileMode:
      enabled: true
      homeInfoParams:
        Title: Xin chào! Tôi là Luân"
        subtitle: "Tôi là Luân! Rất vui được chia sẽ những hiểu biết của tôi về lĩnh vực Data Analyst với mọi người!"
        buttons:
          - name: Bài Viết
            url: Blog
          - name: CV
            url: https://github.com/adityatelange/hugo-PaperMod/wiki/Features#profile-mode
      socialIcons:
        - name: github
          url: "https://github.com/luanletien"
        - name: KoFi
          url: "https://luanletien.com"
        - name: linkedin
          url: "index.xml"
        - name: Rss
          url: "index.xml"
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: WiKi
          url: https://github.com/luanletien
        - name: Discord
          url: https://discord.gg/
